url: https://xykong.xyz
baseurl: ""

layout: stacked
style: dark

author:
  login: kequalxy
  name: kequalxy
  avatar_url: https://github.com/kequalxy.png
  bio:

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9

social_media:
  bilibili: https://space.bilibili.com/1306429853
  telegram: yeqkalxy

